[package]
name = "ffi"
version = "0.1.0"
authors = ["Aki <wuminzhe@gmail.com>"]
edition = "2021"
include = [
    "go.mod",
    "go.sum",
    "build.rs",
    "pkg/**/*",
    "src/**/*",
    "Cargo.toml",
]

[dependencies]
libc = "0.2.71"
anyhow = "1.0.34"
