name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Lint
        run: |
          rustup component add clippy
          cargo clippy --all -- -D warnings

      - name: Run tests
        run: cargo test --release -vv

      - name: Run api tests
        run: cargo test -p api --release -vv

      - name: Run ffi tests
        run: cargo test -p ffi --release -vv
