name: Production
on:
  push:
    tags: ["*"]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io

      - uses: ./.github/actions/docker-build-deploy
        with:
          deploy_phase: production
          docker_registry: quay.io
          trigger_token: ${{ secrets.ITERING_DEPLOYMENT_TRIGGER_TOKEN }}
          trigger_endpoint: ${{ secrets.ITERING_DEPLOYMENT_TRIGGER_ENDPOINT }}
          skip_deploy: true

      - name: Generate template data
        run: |
          echo 'Template data:'
          jq -n \
            --arg tag "$GIT_TAG_NAME" \
            --arg sha "$SHA" \
            '{
              tag: $tag,
              sha: $sha
            }' | tee template_data.json

      - name: Render release page
        uses: jayamanikharyono/jinja-action@v0.1
        with:
          datafile: template_data.json
          path: .maintain/release-template.md

      - name: Publish github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shared/*
          body_path: ".maintain/release-template.md"
          token: ${{ secrets.GITHUB_TOKEN }}

